steps:
  # Step 1: Checkout the repository branch and print the branch name
  - name: 'gcr.io/cloud-builders/git'
    id: 'Checkout repository'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking out branch: $(BRANCH_NAME)"
        git checkout $(BRANCH_NAME)
  
  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${_TAG}'
      - '.'

  # Step 3: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to GCR'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/react-app:$COMMIT_SHA'

  # Step 4: Deploy the Docker image to Google Kubernetes Engine (GKE)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to GKE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to GKE..."
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID
        kubectl set image deployment/react-app react-app=gcr.io/$PROJECT_ID/react-app:$COMMIT_SHA
        kubectl rollout status deployment/react-app
