steps:
  # Install dependencies and build the React app
  - name: 'node:16'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build

  # Copy the build output to a folder
  - name: 'gcr.io/cloud-builders/cp'
    args:
      - '-R'
      - 'build/'
      - '/workspace/build/'

  # Build a Docker image for the app
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${_TAG}'
      - '.'

  # Push the Docker image to Google Container Registry or Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:${_TAG}'

  # Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_IMAGE_NAME}:${_TAG} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated

substitutions:
  _IMAGE_NAME: 'gcr.io/$PROJECT_ID/react-hello-world'
  _TAG: 'latest'
  _SERVICE_NAME: 'react-hello-world-service'
  _REGION: 'us-central1'

timeout: '900s'

# Artifacts to store
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-cloudbuild-artifacts/'
    paths:
      - 'build/**'
